name: build and packet
on: [push]
permissions: write-all

jobs:
  armv7_job:
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu22.04
            python: 3.7
            run-dir: deploy
            target: onnx_profile.py
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run On ${{ matrix.distro }} ${{ matrix.arch }}
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
      - name: Setup Python
        uses: actions/setup-python
        with:
          python-version: ${{ matrix.python }}
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
      - name: Test ${{ matrix.target }}
        working-directory: ${{ matrix.run-dir }}
        run: |
          python ${{ matrix.target }}
      - name: Install PyInstaller
        run: |
          pip install pyinstaller
      - name: Package the ${{ matrix.target }}
        working-directory: ${{ matrix.run-dir }}
        run: |
          pyinstaller ${{ matrix.target }} –clean -add-data=:model_data
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.run-dir }}/dist/*
      
