name: build and packet
on: [push]
permissions: write-all

jobs:
  armv7_job:
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run On ${{ matrix.distro }} ${{ matrix.arch }}
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
